// <auto-generated />
namespace GopherGmConnect.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PlayerContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlayerContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201304030201301_PlayerContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
